import './globals.css'
import type { Metadata } from 'next'
import styles from './page.module.css'
import { Inter } from 'next/font/google'
import Link from 'next/link'
import Providers from './provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html>
      <body className={inter.className}>
        <div className={styles.description}>
          <div className={styles.navbar}>
            <div>
              <button className={styles.button}><Link href="./">open</Link></button>
            </div>
            <div>
              <button className={styles.button}><Link href="./history">closed</Link></button>
            </div>
          </div>
        </div>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
