version: '3.8'
services:
  db:
    image: postgres:15.4
    restart: unless-stopped
    volumes:
      - ./database:/var/lib/postgresql/data
      - ./infrastructure/scripts/create-multiple-postgresql-databases.sh:/docker-entrypoint-initdb.d/create-multiple-postgresql-databases.sh:rw
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=ProcessCubeAdmin1
      - POSTGRES_MULTIPLE_DATABASES=engine,authority
    ports:
      - 5432:5432

  authority:
    image: 5minds/processcube_authority:2023-2
    ports:
      - 11560:11560
    restart: unless-stopped
    environment:
      CONFIG_PATH: /etc/authority/config/config.json
      UPE_SEED_PATH: /etc/authority/config/upeSeedingData.json
      LOG_LEVEL: info
    volumes:
      - ./.processcube/authority/config.json:/etc/authority/config/config.json
      - ./.processcube/authority/upeSeedingData.json:/etc/authority/config/upeSeedingData.json

  engine:
    image: 5minds/processcube_engine:2023-2
    restart: unless-stopped
    ports:
      - 8000:8000
    volumes:
      - ./.processcube/engine/config.json:/etc/engine/config.json:ro
      - ./processes:/processes:ro
    command: --seed-dir=/processes --port 8000
    environment:
      CONFIG_PATH: /etc/engine/config.json

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: 5minds/processcubeio-app
    restart: unless-stopped
    command: ${COMMAND:-npm run dev}
    volumes:
      - ./:/src
      - /src/node_modules
      - /src/.next
    working_dir: /src
    ports:
      - '3000:3000'
    depends_on:
      - authority
      - engine
